name: app_ui

on:
  pull_request:
    paths:
      - "packages/app_ui/**"
      - ".github/workflows/app_ui.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: ./packages/app_ui
    runs-on: ubuntu-latest

    steps:
      - uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
        with:
          flutter_channel: stable
          flutter_version: 3.0.4
          min_coverage: 0
